CREATE SEQUENCE user_id_seq START 1000 INCREMENT 50;
DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
ID INT AUTO_INCREMENT  PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(150) NOT NULL,
LOCATION VARCHAR(30) NOT NULL,
DEPARTMENT VARCHAR(50) NOT NULL
);